name: cochlea-net

channels:
  - conda-forge

dependencies:
  - cluster_tools >=0.5.1
  - mobie_utils
  - pip
  - pooch
  - pybdv
  - pytorch
  - scikit-image
  - seaborn
  - s3fs
  - torch_em
  - trimesh
  - z5py
  # Don't install zarr v3, which is not yet compatible with all dependencies.
  - zarr <3
